import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {recordSnapshot} from '../src/intelligence/rules.js';
const ROOT=path.resolve(new URL('..',import.meta.url).pathname);
async function availablePort(){const s=net.createServer();s.listen(0,'127.0.0.1');await once(s,'listening');const p=s.address().port;await new Promise(r=>s.close(r));return p;}
test('HTTP feature requires login, administrator mutations, same-origin and CSRF; operator can review',async t=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'amzguard-intel-http-'));
 fs.cpSync(path.join(ROOT,'src'),path.join(temp,'src'),{recursive:true});
 fs.writeFileSync(path.join(temp,'package.json'),'{"type":"module"}');
 fs.symlinkSync(path.join(ROOT,'node_modules'),path.join(temp,'node_modules'),'dir');
 fs.mkdirSync(path.join(temp,'config'));fs.writeFileSync(path.join(temp,'config','config.json'),JSON.stringify({paths:{outDir:'out'}}));
 fs.writeFileSync(path.join(temp,'config','stores.json'),JSON.stringify([{key:'US-A',name:'Fixture',id:'fixture',market:'US'}]));
 const port=await availablePort(),base=`http://127.0.0.1:${port}`;
 const child=spawn(process.execPath,['src/server.js'],{cwd:temp,env:{...process.env,NODE_ENV:'test',HOST:'127.0.0.1',PORT:String(port),DASHBOARD_USERNAME:'test-admin',DASHBOARD_PASSWORD:'fixture-only-password',DASHBOARD_SESSION_SECRET:'fixture-session-secret-with-40-characters',AMZGUARD_PRODUCT_UPLOAD_ENABLED:'0',AMZGUARD_PRODUCT_UPLOAD_EXECUTION_ENABLED:'0'},stdio:['ignore','pipe','pipe']});
 let errors='';child.stderr.on('data',s=>{errors+=s;});
 t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');fs.rmSync(temp,{recursive:true,force:true});});
 for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,50));if(i===99)throw new Error('Fixture server failed: '+errors);}
 assert.equal((await fetch(base+'/api/intelligence')).status,401);
 const login=await fetch(base+'/login',{method:'POST',body:new URLSearchParams({username:'test-admin',password:'fixture-only-password'}),redirect:'manual'});
 assert.equal(login.status,303);const cookie=login.headers.get('set-cookie').split(';')[0];
 const get=async url=>fetch(base+url,{headers:{cookie}});
 const context=await (await get('/api/intelligence')).json();assert.equal(context.canManage,true);assert.equal(context.targets.length,0);
 const legacy=await fetch(base+'/intelligence',{headers:{cookie},redirect:'manual'});
 assert.equal(legacy.status,303);assert.equal(legacy.headers.get('location'),'/#intelligence');
 const page=await get('/');
 assert.match(page.headers.get('content-security-policy'), /frame-ancestors 'none'/);
 assert.equal(page.headers.get('cache-control'),'no-store');
 const markup=await page.text();
 assert.match(markup,/<a href="#intelligence" data-view="intelligence">/);
 assert.match(markup,/data-view-panel="intelligence"/);
 assert.match(markup,/<template id="intelligenceTemplate">[\s\S]*变化有依据/);
 assert.equal([...markup.matchAll(/<nav class="nav"/g)].length,1);
 assert.match(await (await get('/assets/intelligence-client.js')).text(),/use strict/);
 const payload={asin:'B012345678',storeKey:'US-A',role:'own',productLine:'Test',enabled:true};
 const url=base+'/api/intelligence/targets';
 assert.equal((await fetch(url,{method:'POST',headers:{cookie,'Content-Type':'application/json',Origin:base},body:JSON.stringify(payload)})).status,403);
 assert.equal((await fetch(url,{method:'POST',headers:{cookie,'Content-Type':'application/json',Origin:'https://other.invalid','X-Amzguard-Csrf':context.csrf},body:JSON.stringify(payload)})).status,403);
 const headers={cookie,'Content-Type':'application/json',Origin:base,'X-Amzguard-Csrf':context.csrf};
 const create=await fetch(url,{method:'POST',headers,body:JSON.stringify(payload)});assert.equal(create.status,200);const item=(await create.json()).result;
 assert.equal((await get('/api/intelligence/targets/'+item.id+'/history')).status,200);
 assert.equal((await fetch(base+'/api/intelligence/run',{method:'POST',headers,body:'{}'})).status,202);
 const user=await fetch(base+'/api/users',{method:'POST',headers,body:JSON.stringify({username:'operator1',password:'operator-fixture-password',role:'operator'})});assert.equal(user.status,201);
 const opLogin=await fetch(base+'/login',{method:'POST',body:new URLSearchParams({username:'operator1',password:'operator-fixture-password'}),redirect:'manual'});
 const opCookie=opLogin.headers.get('set-cookie').split(';')[0];
 const opCtx=await (await fetch(base+'/api/intelligence',{headers:{cookie:opCookie}})).json();assert.equal(opCtx.canManage,false);
 const at=Date.now();
 for(const [i,cents] of [2000,2300,2300].entries())recordSnapshot(path.join(temp,'out'),item,{observedAt:new Date(at-(3-i)*120000).toISOString(),status:'COMPLETE',contextKey:'fixture',priceCents:cents,availability:'AVAILABLE',trusted:{price:true,availability:true},issues:[],evidence:{}});
 const event=(await (await get('/api/intelligence')).json()).events[0];
 const review=await fetch(base+'/api/intelligence/events/'+event.id+'/review',{method:'PUT',headers:{...headers,cookie:opCookie,'X-Amzguard-Csrf':opCtx.csrf},body:JSON.stringify({version:0,status:'useful',note:'operator fixture'})});
 assert.equal(review.status,200);assert.equal((await review.json()).result.review.by,'operator1');
 assert.equal((await fetch(url,{method:'POST',headers:{...headers,cookie:opCookie,'X-Amzguard-Csrf':opCtx.csrf},body:JSON.stringify({...payload,asin:'B076543210'})})).status,403);
 assert.equal((await fetch(base+'/api/intelligence/settings',{method:'PUT',headers,body:JSON.stringify({revision:0,autoCollect:true})})).status,409);
 assert.equal(fs.existsSync(path.join(temp,'out','channels')),false);
});
