'use strict';
(() => {
  let view=null;
  // Mount once for this dashboard session. Navigation only hides the host;
  // its DOM, filters and event handlers stay alive inside the shadow root.
  window.amzIntelligence={
    activate(){
      if(view)return;
      const host=document.getElementById('intelligenceView');
      const root=host.attachShadow({mode:'open'});
      root.append(document.getElementById('intelligenceTemplate').content.cloneNode(true));
      view=install(root,host);
    },
    refresh(){return view?.refresh();},
    suspend(){view?.suspend();}
  };
  function install(root,host){
  const $=s=>root.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const time=s=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'尚未采集';
  const money=v=>typeof v==='number'?`$${(v/100).toFixed(2)}`:'待核验';
  const availability=s=>({AVAILABLE:'可购买',UNAVAILABLE:'不可购买',UNKNOWN:'待核验'}[s]||'待核验');
  const evidenceStatus=s=>s.error||s.issues?.join('；')||(s.status==='COMPLETE'?'双路证据完整':'证据缺失或未完整取得，待核验');
  const types={PRICE_UP:'展示价上升',PRICE_DOWN:'价格竞争变化',UNAVAILABLE:'可购买状态下降',AVAILABLE:'恢复可购买'};
  const lifecycle={ACTIVE:'已确认变化',SUPERSEDED:'已有后续变化',EXPIRED:'历史记录'};
  const assessment={PENDING:'承接条件待核验',READY:'条件满足 · 待运营复核',UNMET:'承接条件未满足',OBSERVATION:'自有商品观察'};
  let data=null,activeTab='compare',search='',filter='all',loading=false,detailTarget=null,historyPage=1;
  function message(s,bad=false){const el=$('#message');el.textContent=s;el.classList.toggle('bad',bad);el.hidden=!s;}
  async function api(route='',method='GET',payload){const r=await fetch('/api/intelligence'+route,{method,cache:'no-store',headers:method==='GET'?{}:{'Content-Type':'application/json','X-Amzguard-Csrf':data?.csrf||''},body:payload===undefined?undefined:JSON.stringify(payload)});if(r.status===401){location.href='/login';throw new Error('登录已过期');}const body=await r.json();if(!r.ok)throw new Error(body.error||`请求失败 ${r.status}`);return body;}
  function filteredTarget(t){return [t.asin,t.label,t.productLine].join(' ').toLowerCase().includes(search);}
  function renderComparisons(){
    const b=data.salesBaseline;
    $('#baselineInfo').textContent=b?`${b.storeKey} · 本店销量区间 ${b.period.start} 至 ${b.period.end} · 已核验 ${b.products.length} 个子 ASIN · ${b.coverage==='FULL_PAGE'?'完整采集':'部分核验'} · 选品快照 ${time(b.observedAt)}（固定区间，不随定时采样更新）`:'尚未导入本店选品销量快照；可先建立商品与竞品档案。';
    const groups=(data.comparisons||[]).filter(g=>[g.own,...g.competitors].some(filteredTarget));
    function row(t,kind,baseline){
      const badge=t.latest?.salesTrend,known=badge&&!t.stale;
      const spec=[t.model,t.capacity,t.color,t.packCount?`${t.packCount} 件装`:'装数待核验'].filter(Boolean).join(' · ');
      return `<tr class="${kind==='own'?'own-row':''}"><td><span class="tag ${kind==='own'?'good':'pending'}">${kind==='own'?'本店主销':t.specsMatch?'同规格竞品':'同型号参考'}</span><b>${esc(t.label||t.latest?.title||t.asin)}</b><small class="mono">${esc(t.asin)}</small><small>${esc(spec)}</small></td><td><b>${baseline?baseline.unitsOrdered.toLocaleString()+' 件':'—'}</b><small>${kind==='own'?(baseline?'选品区间已订购商品数量':'本店销量待取得'):'竞品真实销量未知'}</small></td><td><b>${known?esc(badge.badgeText.replace(/ bought in past month$/i,'')):'待核验'}</b><small>${known?'过去一个月购买量提示':t.stale?'采样缺失或已过期':'未取得可核验购买量提示'}</small></td><td><b>${esc(money(t.stale?null:t.latest?.priceCents))}</b><small>${esc(t.stale?'当前状态待核验':availability(t.latest?.availability))}</small></td><td><small>${esc(time(t.latest?.observedAt))}</small><button data-history="${t.id}">查看证据</button></td></tr>`;
    }
    $('#comparisons').innerHTML=groups.length?groups.map(g=>`<article class="comparison-group"><div class="comparison-title"><h3>${esc(g.own.storeKey)} · ${esc(g.own.productLine)}</h3><small>${g.competitors.length} 个竞品 · 按可信购买量档位排列</small></div><div class="table-scroll"><table><thead><tr><th scope="col">商品 / 可比规格</th><th scope="col">本店选品销量</th><th scope="col">公开购买量提示</th><th scope="col">最近展示价</th><th scope="col">采样与证据</th></tr></thead><tbody>${row(g.own,'own',g.baseline)}${g.competitors.map(t=>row(t,'competitor')).join('')}</tbody></table></div>${g.competitors.length?'':'<p class="comparison-note">此商品尚未关联竞品，可在商品档案中添加并核对规格。</p>'}</article>`).join(''):'<div class="empty"><b>从一家店的主销商品开始</b><p>先添加本店商品，再为竞品选择对应商品，即可在这里对照查看。</p><button data-show-targets>查看商品档案</button></div>';
  }
  function render(){if(!data)return;
    renderComparisons();
    $('#filter').hidden=activeTab==='compare';
    $('#updated').textContent='更新于 '+new Date().toLocaleTimeString('zh-CN',{hour12:false});
    $('#stats').innerHTML=[['观察商品',data.summary.targets],['启用监测',data.summary.enabled],['待复核变化',data.summary.unreviewed],['数据待补全',data.summary.collectionGaps]].map(([label,n],i)=>`<article class="${i===3?'gap':''}"><small>${label}</small><strong>${n}</strong></article>`).join('');
    const r=data.run;
    $('#runTitle').textContent=r?.state==='RUNNING'?`正在采集 · ${r.completed||0}/${r.total||0}`:data.request?'采集请求已排队':r?.state==='DEFERRED'?'采集已延后':r?.state==='INTERRUPTED'?'上次采集已中断':r?.state==='COMPLETED'?'最近采集已完成':r?.state==='PARTIAL'?'最近采集存在数据缺口':'等待首次采集';
    $('#runDetail').textContent=r?.message|| (r?.finishedAt?'完成于 '+time(r.finishedAt):'保存商品档案后可立即采集，或启用每 12 小时监测。忙碌时自动延后。');
    $('#autoCollect').checked=data.settings.autoCollect;$('#autoCollect').disabled=!data.canManage;
    $('#runNow').disabled=!data.canManage||!data.summary.enabled||!!data.request||r?.state==='RUNNING';
    $('#addTarget').disabled=!data.canManage;
    const events=data.events.filter(e=>e.target&&filteredTarget(e.target)&&(filter!=='pending'||e.review.status==='unreviewed')&&(filter!=='useful'||e.review.status==='useful')&&(filter!=='gaps'||!e.actionable||e.assessment?.status==='PENDING'));
    $('#events').innerHTML=events.length?events.map(e=>`<article class="event"><div><span class="tag ${e.type==='PRICE_DOWN'?'warn':''}">${esc(types[e.type])}</span><h3>${esc(e.target.label||e.target.asin)}</h3><small>${esc(e.target.productLine)} · ${esc(e.target.asin)}</small></div><div><div class="values">${esc(e.field==='price'?money(e.before.priceCents):availability(e.before.availability))}<em>→</em>${esc(e.field==='price'?money(e.after.priceCents):availability(e.after.availability))}</div><small>${esc(time(e.createdAt))} · ${esc(lifecycle[e.lifecycle])}</small></div><div><span class="tag ${e.actionable&&e.assessment?.status==='READY'?'good':'pending'}">${esc(e.actionable?assessment[e.assessment?.status]||'待核验':'仅供历史复核')}</span><small>${esc({unreviewed:'尚未人工复核',useful:'已标记有效',dismissed:'已标记无效'}[e.review.status])}</small></div><button data-event="${e.id}">查看证据</button></article>`).join(''):`<div class="empty"><b>${data.targets.length?'暂未发现符合条件的变化':'从一组可比商品开始'}</b><p>${data.targets.length?'首次可信采样建立基线；变化经过后续两次采样确认后出现在这里。采样失败会显示在商品档案，不能解释为没有变化。':'先添加自有商品与直接竞品，记录双方型号和规格。完成只读采样后，这里会显示变化证据及待核验机会。'}</p><button data-show-targets>查看商品档案</button></div>`;
    const targets=data.targets.filter(t=>filteredTarget(t)&&(filter!=='gaps'||t.stale||!t.latest?.trusted?.price||!t.latest?.trusted?.availability));
    $('#targets').innerHTML=targets.map(t=>`<tr><td><b title="${esc(t.label)}">${esc(t.label||t.latest?.title||t.asin)}</b><small class="mono">${esc(t.asin)}</small></td><td>${esc(t.productLine)}<small>${t.role==='own'?'自有商品':'竞品'} · ${t.enabled?'监测中':'已停用'} · ${esc(t.storeKey)}</small></td><td>${esc(money(t.latest?.priceCents))}<small>${t.latest?.trusted?.price?'一次性购买展示价':'报价证据待补全'}</small></td><td><span class="tag ${t.latest?.availability==='AVAILABLE'?'good':'pending'}">${esc(availability(t.latest?.availability))}</span>${t.pending.length?'<small>变化待再次采样确认</small>':''}</td><td>${esc(time(t.latest?.observedAt))}<small>${t.stale?'数据尚未取得或已过期':esc(t.latest?.status==='COMPLETE'?'双路证据完整':t.latest?.issues?.join('；')||'部分字段待核验')}</small></td><td><button data-history="${t.id}">历史</button>${data.canManage?`<button data-edit="${t.id}">编辑</button>${t.role==='own'?`<button data-business="${t.id}">经营条件</button>`:''}`:''}</td></tr>`).join('');
    $('#targetsEmpty').innerHTML=targets.length?'':'<div class="empty"><b>还没有符合筛选的商品</b><p>管理员可使用“添加观察商品”建立独立档案。</p></div>';
  }
  async function load(){if(loading)return;loading=true;try{data=await api();render();}catch(e){message(e.message,true);}finally{loading=false;}}
  function tab(name){activeTab=name;$('#filter').hidden=name==='compare';$('#comparePanel').hidden=name!=='compare';$('#eventsPanel').hidden=name!=='events';$('#targetsPanel').hidden=name!=='targets';root.querySelectorAll('[data-tab]').forEach(el=>{const selected=el.dataset.tab===name;el.classList.toggle('selected',selected);el.setAttribute('aria-selected',String(selected));});}
  function mapOptions(){const f=$('#targetForm');const own=data.targets.filter(t=>t.role==='own'&&t.storeKey===f.elements.storeKey.value);const value=f.elements.ownTargetId.value;f.elements.ownTargetId.innerHTML='<option value="">暂不关联</option>'+own.map(t=>`<option value="${t.id}">${esc(t.label||t.asin)} · ${esc(t.asin)}</option>`).join('');if(own.some(t=>t.id===value))f.elements.ownTargetId.value=value;const isOwn=f.elements.role.value==='own';$('#ownMapping').hidden=isOwn;f.elements.matchConfirmed.closest('label').hidden=isOwn;}
  function editTarget(id){const t=data.targets.find(t=>t.id===id), f=$('#targetForm');f.reset();f.querySelector('.form-error').textContent='';$('#editorTitle').textContent=t?'编辑商品档案':'添加观察商品';f.elements.storeKey.innerHTML=data.stores.map(s=>`<option value="${esc(s.key)}">${esc(s.name||s.key)} · ${esc(s.key)}</option>`).join('');for(const k of ['id','version','asin','label','role','storeKey','productLine','model','capacity','color','packCount'])if(t&&f.elements[k])f.elements[k].value=t[k]??'';f.elements.id.value=t?.id||'';f.elements.version.value=t?.version||'';for(const k of ['asin','storeKey','role'])f.elements[k].disabled=!!t;mapOptions();if(t){f.elements.ownTargetId.value=t.ownTargetId||'';f.elements.matchConfirmed.checked=t.matchConfirmed;f.elements.enabled.checked=t.enabled;}$('#editor').showModal();}
  function editBusiness(id){const t=data.targets.find(t=>t.id===id),b=t.business,f=$('#businessForm');f.reset();f.querySelector('.form-error').textContent='';f.elements.id.value=id;f.elements.version.value=b?.version||0;for(const k of ['validHours','inventory','minimumInventory','sellingPrice','unitCost','unitFees','minimumProfit','basis'])if(b)f.elements[k].value=b[k]??'';const d=b?new Date(b.asOf):new Date();f.elements.asOf.value=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#businessEditor').showModal();}
  const number=f=>f.value===''?null:Number(f.value);
  async function submit(form,fn){const button=form.querySelector('[type=submit]');button.disabled=true;form.querySelector('.form-error').textContent='';try{await fn();form.closest('dialog').close();message('已保存在本平台。');await load();}catch(e){form.querySelector('.form-error').textContent=e.message;}finally{button.disabled=false;}}
  $('#targetForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;submit(f,async()=>{const payload={};for(const k of ['asin','label','role','storeKey','productLine','model','capacity','color','ownTargetId'])payload[k]=f.elements[k].value;payload.packCount=number(f.elements.packCount);payload.enabled=f.elements.enabled.checked;payload.matchConfirmed=f.elements.matchConfirmed.checked;if(f.elements.id.value)payload.version=Number(f.elements.version.value);await api('/targets'+(f.elements.id.value?'/'+f.elements.id.value:''),f.elements.id.value?'PUT':'POST',payload);});});
  $('#businessForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;submit(f,async()=>{const payload={version:Number(f.elements.version.value),asOf:new Date(f.elements.asOf.value).toISOString(),basis:f.elements.basis.value};for(const k of ['validHours','inventory','minimumInventory','sellingPrice','unitCost','unitFees','minimumProfit'])payload[k]=number(f.elements[k]);await api('/business/'+f.elements.id.value,'PUT',payload);});});
  function evidence(s,field,label){return `<article><small>${label} · ${esc(time(s.observedAt))}</small><b>${esc(field==='price'?money(s.priceCents):availability(s.availability))}</b><p>${esc(field==='price'?s.evidence?.price?.dom:s.evidence?.availability?.dom)}</p><small>页面文本佐证</small><p>${esc(field==='price'?s.evidence?.price?.text:s.evidence?.availability?.text)}</p><small>环境标识 ${esc(s.contextKey?.slice(0,12)||'未确认')} · ${esc(s.offerBasis||'')}</small></article>`;}
  function openEvent(id){const e=data.events.find(e=>e.id===id);if(!e)return;detailTarget=null;$('#detailTitle').textContent=types[e.type]+' · '+(e.target?.asin||'');$('#detailBody').innerHTML=`<span class="tag">${esc(lifecycle[e.lifecycle])}</span><p>${esc(e.target?.label||e.target?.asin)} · ${esc(e.target?.productLine)}</p><div class="evidence-grid">${evidence(e.before,e.field,'变化前')}${evidence(e.after,e.field,'变化后')}</div><p class="hint">两次确认：${esc(time(e.confirmation.firstAt))} / ${esc(time(e.confirmation.secondAt))}。以上为采样事实；未推断竞品真实库存或销量。</p><h2>当前自身条件</h2>${!e.actionable?'<p class="hint">该记录为历史变化或当前证据不完整，不作为当前机会推荐。</p>':''}${(e.assessment?.conditions||[]).map(c=>`<div class="condition"><span class="tag ${c.status==='PASS'?'good':c.status==='FAIL'?'warn':'pending'}">${{PASS:'满足',FAIL:'未满足',UNKNOWN:'待核验'}[c.status]}</span><div><b>${esc(c.label)}</b><small>${esc(c.detail)}${c.asOf?' · '+esc(time(c.asOf)):''}</small></div></div>`).join('')}<h2 class="review-heading">人工复核</h2><textarea id="reviewNote" rows="3" maxlength="1000" aria-label="复核备注" placeholder="记录这次变化是否值得跟进，以及判断依据">${esc(e.review.note)}</textarea><div class="review-controls"><select id="reviewStatus" aria-label="复核结论"><option value="unreviewed">待复核</option><option value="useful">有效机会</option><option value="dismissed">无效 / 暂不跟进</option></select><button class="primary" id="saveReview">保存复核</button><span id="reviewMessage" role="status"></span></div><p class="hint">${e.review.at?'最近复核：'+esc(e.review.by)+' · '+esc(time(e.review.at)):''}</p>`;$('#reviewStatus').value=e.review.status;$('#saveReview').onclick=async()=>{const b=$('#saveReview');b.disabled=true;try{await api('/events/'+e.id+'/review','PUT',{version:e.review.version,status:$('#reviewStatus').value,note:$('#reviewNote').value});$('#reviewMessage').textContent='已保存';await load();e.review=data.events.find(x=>x.id===id).review;}catch(err){$('#reviewMessage').textContent=err.message;}finally{b.disabled=false;}};$('#detail').showModal();}
  async function openHistory(id,page=1){detailTarget=id;historyPage=page;const t=data.targets.find(t=>t.id===id);$('#detailTitle').textContent='采样历史 · '+t.asin;if(!$('#detail').open)$('#detail').showModal();$('#detailBody').innerHTML='<p class="hint">正在读取历史…</p>';try{const body=await api('/targets/'+id+'/history?page='+page);if(detailTarget!==id||historyPage!==page)return;$('#detailBody').innerHTML=body.records.length?body.records.map(s=>`<article class="history-row"><b>${esc(time(s.observedAt))} · ${esc(money(s.priceCents))} · ${esc(availability(s.availability))}</b><small>${esc(s.title||'')} · ${esc(s.status||'无法读取')}</small><small>${esc(evidenceStatus(s))}</small><details><summary>查看字段证据</summary><pre>${esc(JSON.stringify(s.evidence||{},null,2))}</pre></details></article>`).join('')+`<div class="pager"><button id="prevHistory" ${body.page<=1?'disabled':''}>上一页</button><span>${body.page} / ${body.pages} · ${body.total} 次采样</span><button id="nextHistory" ${body.page>=body.pages?'disabled':''}>下一页</button></div>`:'<div class="empty"><b>尚无采样历史</b><p>首次采样会建立基线。启用监测或发起一次采集后，可在这里查看证据。</p></div>';if($('#prevHistory'))$('#prevHistory').onclick=()=>openHistory(id,page-1);if($('#nextHistory'))$('#nextHistory').onclick=()=>openHistory(id,page+1);}catch(e){$('#detailBody').textContent=e.message;}}
  root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close)$('#'+b.dataset.close).close();if(b.dataset.tab)tab(b.dataset.tab);if(b.hasAttribute('data-show-targets'))tab('targets');if(b.dataset.edit)editTarget(b.dataset.edit);if(b.dataset.business)editBusiness(b.dataset.business);if(b.dataset.history)openHistory(b.dataset.history);if(b.dataset.event)openEvent(b.dataset.event);});
  $('#targetForm').elements.role.addEventListener('change',mapOptions);$('#targetForm').elements.storeKey.addEventListener('change',mapOptions);
  $('#addTarget').onclick=()=>editTarget(null);$('#refresh').onclick=load;
  $('#runNow').onclick=async()=>{const b=$('#runNow');b.disabled=true;try{await api('/run','POST',{});message('已排队；工作者将在空闲窗口执行只读采样。');await load();}catch(e){message(e.message,true);b.disabled=false;}};
  $('#autoCollect').onchange=async()=>{const box=$('#autoCollect');box.disabled=true;try{await api('/settings','PUT',{revision:data.revision,autoCollect:box.checked});message(box.checked?'已启用每 12 小时监测，忙碌时延后。':'已暂停周期采集。');await load();}catch(e){message(e.message,true);box.checked=data.settings.autoCollect;}finally{box.disabled=!data?.canManage;}};
  $('#search').oninput=e=>{search=e.target.value.trim().toLowerCase();render();};$('#filter').onchange=e=>{filter=e.target.value;render();};
  load();setInterval(()=>{if(!document.hidden&&host.getClientRects().length&&!root.querySelector('dialog[open]'))load();},15000);
  return {refresh:load,suspend:()=>root.querySelectorAll('dialog[open]').forEach(dialog=>dialog.close())};
  }
})();
